# Handling Reading
exclude: [LICENSE, README.md]

title: It blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wolforus.github.io" # the base hostname & protocol for your site

github_username:  wolforus


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Outputting
permalink: /post/:title/
paginate: 3
paginate_path: '/page/:num/'
timezone: Europe/Moscow

disqus:
  shortname: wolforus

google_analytics: UA-90456464-1

