collections:
  page_tags:
    output: true
    permalink: /tag/:name/

# Handling Reading
exclude: [LICENSE, README.md]

title: It blog
email: your-email@domain.com
description: >
  It blog description

baseurl: ""
url: "https://wolforus.github.io"

github_username:  wolforus


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist


# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Outputting
permalink: pretty
paginate: 3
paginate_path: '/page/:num/'
timezone: Europe/Moscow

disqus:
  shortname: wolforus

google_analytics: UA-90456464-1
name: wolforus
author: wolforus
copyright: 2016&mdash;2017

sass:
  style: compressed

